version: "3"

services:

  mongodb:
      image: mongo:latest  
      volumes:
        - mongo-data:/data/db 
      ports:
        - "27017:27017" 

  client-frontend:
    build:
      context:  ./client  
    image: haniyatj/final:01-frontend
    environment:
     MONGO_URL: mongodb://mongodb:27017/ 
    ports:
      - "8081:1169"

  classroom-backend:
    build:
      context: ./Classrooms
    image: haniyatj/final:01-backend
    environment:
      MONGO_URL: mongodb://mongodb:27017/ 
    ports:
      - "8082:4001"

  event-backend:
    build:
      context: ./event-bus
    image: haniyatj/final:02-backend
    environment:
      MONGO_URL: mongodb://mongodb:27017/ 
    ports:
      - "8084:4009"

  post-backend:
    build:
      context: ./Post
    image: haniyatj/final:03-backend
    environment:
     MONGO_URL: mongodb://mongodb:27017/ 
    ports:
      - "8084:4002"

  auth-backend:
  build:
    context: ./Auth
  image: haniyatj/final:04-backend
  environment:
    MONGO_URL: mongodb://mongodb:27017/ 
  ports:
    - "8084:4000"



