apiVersion: v1
kind: Service
metadata:
  name: all-services-service
spec:
  type: NodePort
  selector:
    app: all-services
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: client-frontend
      protocol: TCP
      port: 8081
      targetPort: 1169
    - name: classroom-backend
      protocol: TCP
      port: 8000
      targetPort: 4001
    - name: event-backend
      protocol: TCP
      port: 8000
      targetPort: 4009
    - name: post-backend
      protocol: TCP
      port: 8000
      targetPort: 4002
    - name: auth-backend
      protocol: TCP
      port: 8000
      targetPort: 4000
