apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode-01
  template:
    metadata:
      labels:
        app: episode-01
    spec:
      containers:
        - name: episode-01-backend
          image: haniyatj/practice:01-backend
          ports:
            - name: backendport
              containerPort: 8000
          env:
            - name: MONGO_DB_SECRET
              value: mongodb+srv://haniyatariq65:haniya@cluster0.vg8x7b1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        - name: episode-01-frontend
          image: haniyatj/practice:01-frontend
          ports:
            - name: frontendport
              containerPort: 3000

      nodeSelector:
        kubernetes.io/hostname: minikube-m02